//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	apiv1beta1 "sigs.k8s.io/cluster-api-provider-gcp/api/v1beta1"
	corev1beta1 "sigs.k8s.io/cluster-api/api/core/v1beta1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticatorGroupConfig) DeepCopyInto(out *AuthenticatorGroupConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticatorGroupConfig.
func (in *AuthenticatorGroupConfig) DeepCopy() *AuthenticatorGroupConfig {
	if in == nil {
		return nil
	}
	out := new(AuthenticatorGroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetwork) DeepCopyInto(out *ClusterNetwork) {
	*out = *in
	if in.PrivateCluster != nil {
		in, out := &in.PrivateCluster, &out.PrivateCluster
		*out = new(PrivateCluster)
		**out = **in
	}
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(ClusterNetworkPod)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ClusterNetworkService)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetwork.
func (in *ClusterNetwork) DeepCopy() *ClusterNetwork {
	if in == nil {
		return nil
	}
	out := new(ClusterNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetworkPod) DeepCopyInto(out *ClusterNetworkPod) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetworkPod.
func (in *ClusterNetworkPod) DeepCopy() *ClusterNetworkPod {
	if in == nil {
		return nil
	}
	out := new(ClusterNetworkPod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetworkService) DeepCopyInto(out *ClusterNetworkService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetworkService.
func (in *ClusterNetworkService) DeepCopy() *ClusterNetworkService {
	if in == nil {
		return nil
	}
	out := new(ClusterNetworkService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSecurity) DeepCopyInto(out *ClusterSecurity) {
	*out = *in
	if in.WorkloadIdentityConfig != nil {
		in, out := &in.WorkloadIdentityConfig, &out.WorkloadIdentityConfig
		*out = new(WorkloadIdentityConfig)
		**out = **in
	}
	if in.AuthenticatorGroupConfig != nil {
		in, out := &in.AuthenticatorGroupConfig, &out.AuthenticatorGroupConfig
		*out = new(AuthenticatorGroupConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSecurity.
func (in *ClusterSecurity) DeepCopy() *ClusterSecurity {
	if in == nil {
		return nil
	}
	out := new(ClusterSecurity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCComputeNetworkSpec) DeepCopyInto(out *GCPKCCComputeNetworkSpec) {
	*out = *in
	if in.AutoCreateSubnetworks != nil {
		in, out := &in.AutoCreateSubnetworks, &out.AutoCreateSubnetworks
		*out = new(bool)
		**out = **in
	}
	if in.AdditionalConfig != nil {
		in, out := &in.AdditionalConfig, &out.AdditionalConfig
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCComputeNetworkSpec.
func (in *GCPKCCComputeNetworkSpec) DeepCopy() *GCPKCCComputeNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCComputeNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCComputeSubnetworkSpec) DeepCopyInto(out *GCPKCCComputeSubnetworkSpec) {
	*out = *in
	if in.SecondaryIpRange != nil {
		in, out := &in.SecondaryIpRange, &out.SecondaryIpRange
		*out = make([]KCCSecondaryIPRange, len(*in))
		copy(*out, *in)
	}
	out.NetworkRef = in.NetworkRef
	if in.AdditionalConfig != nil {
		in, out := &in.AdditionalConfig, &out.AdditionalConfig
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCComputeSubnetworkSpec.
func (in *GCPKCCComputeSubnetworkSpec) DeepCopy() *GCPKCCComputeSubnetworkSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCComputeSubnetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCContainerClusterResource) DeepCopyInto(out *GCPKCCContainerClusterResource) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCContainerClusterResource.
func (in *GCPKCCContainerClusterResource) DeepCopy() *GCPKCCContainerClusterResource {
	if in == nil {
		return nil
	}
	out := new(GCPKCCContainerClusterResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCContainerClusterSpec) DeepCopyInto(out *GCPKCCContainerClusterSpec) {
	*out = *in
	if in.InitialNodeCount != nil {
		in, out := &in.InitialNodeCount, &out.InitialNodeCount
		*out = new(int32)
		**out = **in
	}
	if in.RemoveDefaultNodePool != nil {
		in, out := &in.RemoveDefaultNodePool, &out.RemoveDefaultNodePool
		*out = new(bool)
		**out = **in
	}
	out.NetworkRef = in.NetworkRef
	out.SubnetworkRef = in.SubnetworkRef
	if in.IpAllocationPolicy != nil {
		in, out := &in.IpAllocationPolicy, &out.IpAllocationPolicy
		*out = new(KCCIPAllocationPolicy)
		**out = **in
	}
	if in.ReleaseChannel != nil {
		in, out := &in.ReleaseChannel, &out.ReleaseChannel
		*out = new(KCCReleaseChannel)
		**out = **in
	}
	if in.WorkloadIdentityConfig != nil {
		in, out := &in.WorkloadIdentityConfig, &out.WorkloadIdentityConfig
		*out = new(KCCWorkloadIdentityConfig)
		**out = **in
	}
	if in.PrivateClusterConfig != nil {
		in, out := &in.PrivateClusterConfig, &out.PrivateClusterConfig
		*out = new(KCCPrivateClusterConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MasterAuthorizedNetworksConfig != nil {
		in, out := &in.MasterAuthorizedNetworksConfig, &out.MasterAuthorizedNetworksConfig
		*out = new(KCCMasterAuthorizedNetworksConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalConfig != nil {
		in, out := &in.AdditionalConfig, &out.AdditionalConfig
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCContainerClusterSpec.
func (in *GCPKCCContainerClusterSpec) DeepCopy() *GCPKCCContainerClusterSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCContainerClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCContainerNodePoolResource) DeepCopyInto(out *GCPKCCContainerNodePoolResource) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCContainerNodePoolResource.
func (in *GCPKCCContainerNodePoolResource) DeepCopy() *GCPKCCContainerNodePoolResource {
	if in == nil {
		return nil
	}
	out := new(GCPKCCContainerNodePoolResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCContainerNodePoolSpec) DeepCopyInto(out *GCPKCCContainerNodePoolSpec) {
	*out = *in
	if in.InitialNodeCount != nil {
		in, out := &in.InitialNodeCount, &out.InitialNodeCount
		*out = new(int32)
		**out = **in
	}
	if in.NodeLocations != nil {
		in, out := &in.NodeLocations, &out.NodeLocations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.ClusterRef = in.ClusterRef
	if in.NodeConfig != nil {
		in, out := &in.NodeConfig, &out.NodeConfig
		*out = new(KCCNodeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(KCCNodePoolAutoscaling)
		(*in).DeepCopyInto(*out)
	}
	if in.Management != nil {
		in, out := &in.Management, &out.Management
		*out = new(KCCNodePoolManagement)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalConfig != nil {
		in, out := &in.AdditionalConfig, &out.AdditionalConfig
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCContainerNodePoolSpec.
func (in *GCPKCCContainerNodePoolSpec) DeepCopy() *GCPKCCContainerNodePoolSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCContainerNodePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedCluster) DeepCopyInto(out *GCPKCCManagedCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedCluster.
func (in *GCPKCCManagedCluster) DeepCopy() *GCPKCCManagedCluster {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedClusterInitializationStatus) DeepCopyInto(out *GCPKCCManagedClusterInitializationStatus) {
	*out = *in
	if in.Provisioned != nil {
		in, out := &in.Provisioned, &out.Provisioned
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedClusterInitializationStatus.
func (in *GCPKCCManagedClusterInitializationStatus) DeepCopy() *GCPKCCManagedClusterInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedClusterInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedClusterList) DeepCopyInto(out *GCPKCCManagedClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPKCCManagedCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedClusterList.
func (in *GCPKCCManagedClusterList) DeepCopy() *GCPKCCManagedClusterList {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedClusterSpec) DeepCopyInto(out *GCPKCCManagedClusterSpec) {
	*out = *in
	in.Network.DeepCopyInto(&out.Network)
	in.Subnetwork.DeepCopyInto(&out.Subnetwork)
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedClusterSpec.
func (in *GCPKCCManagedClusterSpec) DeepCopy() *GCPKCCManagedClusterSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedClusterStatus) DeepCopyInto(out *GCPKCCManagedClusterStatus) {
	*out = *in
	if in.Initialization != nil {
		in, out := &in.Initialization, &out.Initialization
		*out = new(GCPKCCManagedClusterInitializationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.FailureDomains != nil {
		in, out := &in.FailureDomains, &out.FailureDomains
		*out = make(corev1beta1.FailureDomains, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedClusterStatus.
func (in *GCPKCCManagedClusterStatus) DeepCopy() *GCPKCCManagedClusterStatus {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedClusterTemplate) DeepCopyInto(out *GCPKCCManagedClusterTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedClusterTemplate.
func (in *GCPKCCManagedClusterTemplate) DeepCopy() *GCPKCCManagedClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedClusterTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedClusterTemplateList) DeepCopyInto(out *GCPKCCManagedClusterTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPKCCManagedClusterTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedClusterTemplateList.
func (in *GCPKCCManagedClusterTemplateList) DeepCopy() *GCPKCCManagedClusterTemplateList {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedClusterTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedClusterTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedClusterTemplateResource) DeepCopyInto(out *GCPKCCManagedClusterTemplateResource) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedClusterTemplateResource.
func (in *GCPKCCManagedClusterTemplateResource) DeepCopy() *GCPKCCManagedClusterTemplateResource {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedClusterTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedClusterTemplateResourceSpec) DeepCopyInto(out *GCPKCCManagedClusterTemplateResourceSpec) {
	*out = *in
	in.Network.DeepCopyInto(&out.Network)
	in.Subnetwork.DeepCopyInto(&out.Subnetwork)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedClusterTemplateResourceSpec.
func (in *GCPKCCManagedClusterTemplateResourceSpec) DeepCopy() *GCPKCCManagedClusterTemplateResourceSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedClusterTemplateResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedClusterTemplateSpec) DeepCopyInto(out *GCPKCCManagedClusterTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedClusterTemplateSpec.
func (in *GCPKCCManagedClusterTemplateSpec) DeepCopy() *GCPKCCManagedClusterTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedClusterTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedControlPlane) DeepCopyInto(out *GCPKCCManagedControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedControlPlane.
func (in *GCPKCCManagedControlPlane) DeepCopy() *GCPKCCManagedControlPlane {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedControlPlaneInitializationStatus) DeepCopyInto(out *GCPKCCManagedControlPlaneInitializationStatus) {
	*out = *in
	if in.ControlPlaneInitialized != nil {
		in, out := &in.ControlPlaneInitialized, &out.ControlPlaneInitialized
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedControlPlaneInitializationStatus.
func (in *GCPKCCManagedControlPlaneInitializationStatus) DeepCopy() *GCPKCCManagedControlPlaneInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedControlPlaneInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedControlPlaneList) DeepCopyInto(out *GCPKCCManagedControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPKCCManagedControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedControlPlaneList.
func (in *GCPKCCManagedControlPlaneList) DeepCopy() *GCPKCCManagedControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedControlPlaneSpec) DeepCopyInto(out *GCPKCCManagedControlPlaneSpec) {
	*out = *in
	in.ContainerCluster.DeepCopyInto(&out.ContainerCluster)
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedControlPlaneSpec.
func (in *GCPKCCManagedControlPlaneSpec) DeepCopy() *GCPKCCManagedControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedControlPlaneStatus) DeepCopyInto(out *GCPKCCManagedControlPlaneStatus) {
	*out = *in
	if in.Initialization != nil {
		in, out := &in.Initialization, &out.Initialization
		*out = new(GCPKCCManagedControlPlaneInitializationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalManagedControlPlane != nil {
		in, out := &in.ExternalManagedControlPlane, &out.ExternalManagedControlPlane
		*out = new(bool)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedControlPlaneStatus.
func (in *GCPKCCManagedControlPlaneStatus) DeepCopy() *GCPKCCManagedControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedControlPlaneTemplate) DeepCopyInto(out *GCPKCCManagedControlPlaneTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedControlPlaneTemplate.
func (in *GCPKCCManagedControlPlaneTemplate) DeepCopy() *GCPKCCManagedControlPlaneTemplate {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedControlPlaneTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedControlPlaneTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedControlPlaneTemplateList) DeepCopyInto(out *GCPKCCManagedControlPlaneTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPKCCManagedControlPlaneTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedControlPlaneTemplateList.
func (in *GCPKCCManagedControlPlaneTemplateList) DeepCopy() *GCPKCCManagedControlPlaneTemplateList {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedControlPlaneTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedControlPlaneTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedControlPlaneTemplateResource) DeepCopyInto(out *GCPKCCManagedControlPlaneTemplateResource) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedControlPlaneTemplateResource.
func (in *GCPKCCManagedControlPlaneTemplateResource) DeepCopy() *GCPKCCManagedControlPlaneTemplateResource {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedControlPlaneTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedControlPlaneTemplateResourceSpec) DeepCopyInto(out *GCPKCCManagedControlPlaneTemplateResourceSpec) {
	*out = *in
	in.ContainerCluster.DeepCopyInto(&out.ContainerCluster)
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedControlPlaneTemplateResourceSpec.
func (in *GCPKCCManagedControlPlaneTemplateResourceSpec) DeepCopy() *GCPKCCManagedControlPlaneTemplateResourceSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedControlPlaneTemplateResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedControlPlaneTemplateSpec) DeepCopyInto(out *GCPKCCManagedControlPlaneTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedControlPlaneTemplateSpec.
func (in *GCPKCCManagedControlPlaneTemplateSpec) DeepCopy() *GCPKCCManagedControlPlaneTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedControlPlaneTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedMachinePool) DeepCopyInto(out *GCPKCCManagedMachinePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedMachinePool.
func (in *GCPKCCManagedMachinePool) DeepCopy() *GCPKCCManagedMachinePool {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedMachinePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedMachinePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedMachinePoolInitializationStatus) DeepCopyInto(out *GCPKCCManagedMachinePoolInitializationStatus) {
	*out = *in
	if in.Provisioned != nil {
		in, out := &in.Provisioned, &out.Provisioned
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedMachinePoolInitializationStatus.
func (in *GCPKCCManagedMachinePoolInitializationStatus) DeepCopy() *GCPKCCManagedMachinePoolInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedMachinePoolInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedMachinePoolList) DeepCopyInto(out *GCPKCCManagedMachinePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPKCCManagedMachinePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedMachinePoolList.
func (in *GCPKCCManagedMachinePoolList) DeepCopy() *GCPKCCManagedMachinePoolList {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedMachinePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedMachinePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedMachinePoolSpec) DeepCopyInto(out *GCPKCCManagedMachinePoolSpec) {
	*out = *in
	in.NodePool.DeepCopyInto(&out.NodePool)
	if in.ProviderIDList != nil {
		in, out := &in.ProviderIDList, &out.ProviderIDList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedMachinePoolSpec.
func (in *GCPKCCManagedMachinePoolSpec) DeepCopy() *GCPKCCManagedMachinePoolSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedMachinePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedMachinePoolStatus) DeepCopyInto(out *GCPKCCManagedMachinePoolStatus) {
	*out = *in
	if in.Initialization != nil {
		in, out := &in.Initialization, &out.Initialization
		*out = new(GCPKCCManagedMachinePoolInitializationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedMachinePoolStatus.
func (in *GCPKCCManagedMachinePoolStatus) DeepCopy() *GCPKCCManagedMachinePoolStatus {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedMachinePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedMachinePoolTemplate) DeepCopyInto(out *GCPKCCManagedMachinePoolTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedMachinePoolTemplate.
func (in *GCPKCCManagedMachinePoolTemplate) DeepCopy() *GCPKCCManagedMachinePoolTemplate {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedMachinePoolTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedMachinePoolTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedMachinePoolTemplateList) DeepCopyInto(out *GCPKCCManagedMachinePoolTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPKCCManagedMachinePoolTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedMachinePoolTemplateList.
func (in *GCPKCCManagedMachinePoolTemplateList) DeepCopy() *GCPKCCManagedMachinePoolTemplateList {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedMachinePoolTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedMachinePoolTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedMachinePoolTemplateResource) DeepCopyInto(out *GCPKCCManagedMachinePoolTemplateResource) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedMachinePoolTemplateResource.
func (in *GCPKCCManagedMachinePoolTemplateResource) DeepCopy() *GCPKCCManagedMachinePoolTemplateResource {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedMachinePoolTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedMachinePoolTemplateResourceSpec) DeepCopyInto(out *GCPKCCManagedMachinePoolTemplateResourceSpec) {
	*out = *in
	in.NodePool.DeepCopyInto(&out.NodePool)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedMachinePoolTemplateResourceSpec.
func (in *GCPKCCManagedMachinePoolTemplateResourceSpec) DeepCopy() *GCPKCCManagedMachinePoolTemplateResourceSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedMachinePoolTemplateResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedMachinePoolTemplateSpec) DeepCopyInto(out *GCPKCCManagedMachinePoolTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedMachinePoolTemplateSpec.
func (in *GCPKCCManagedMachinePoolTemplateSpec) DeepCopy() *GCPKCCManagedMachinePoolTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedMachinePoolTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCNetworkResource) DeepCopyInto(out *GCPKCCNetworkResource) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCNetworkResource.
func (in *GCPKCCNetworkResource) DeepCopy() *GCPKCCNetworkResource {
	if in == nil {
		return nil
	}
	out := new(GCPKCCNetworkResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCSubnetworkResource) DeepCopyInto(out *GCPKCCSubnetworkResource) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCSubnetworkResource.
func (in *GCPKCCSubnetworkResource) DeepCopy() *GCPKCCSubnetworkResource {
	if in == nil {
		return nil
	}
	out := new(GCPKCCSubnetworkResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPMachinePool) DeepCopyInto(out *GCPMachinePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPMachinePool.
func (in *GCPMachinePool) DeepCopy() *GCPMachinePool {
	if in == nil {
		return nil
	}
	out := new(GCPMachinePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPMachinePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPMachinePoolList) DeepCopyInto(out *GCPMachinePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPMachinePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPMachinePoolList.
func (in *GCPMachinePoolList) DeepCopy() *GCPMachinePoolList {
	if in == nil {
		return nil
	}
	out := new(GCPMachinePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPMachinePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPMachinePoolSpec) DeepCopyInto(out *GCPMachinePoolSpec) {
	*out = *in
	if in.ProviderIDList != nil {
		in, out := &in.ProviderIDList, &out.ProviderIDList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Subnet != nil {
		in, out := &in.Subnet, &out.Subnet
		*out = new(string)
		**out = **in
	}
	if in.ImageFamily != nil {
		in, out := &in.ImageFamily, &out.ImageFamily
		*out = new(string)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.AdditionalLabels != nil {
		in, out := &in.AdditionalLabels, &out.AdditionalLabels
		*out = make(apiv1beta1.Labels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AdditionalMetadata != nil {
		in, out := &in.AdditionalMetadata, &out.AdditionalMetadata
		*out = make([]apiv1beta1.MetadataItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PublicIP != nil {
		in, out := &in.PublicIP, &out.PublicIP
		*out = new(bool)
		**out = **in
	}
	if in.AdditionalNetworkTags != nil {
		in, out := &in.AdditionalNetworkTags, &out.AdditionalNetworkTags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResourceManagerTags != nil {
		in, out := &in.ResourceManagerTags, &out.ResourceManagerTags
		*out = make(apiv1beta1.ResourceManagerTags, len(*in))
		copy(*out, *in)
	}
	if in.RootDeviceType != nil {
		in, out := &in.RootDeviceType, &out.RootDeviceType
		*out = new(apiv1beta1.DiskType)
		**out = **in
	}
	if in.AdditionalDisks != nil {
		in, out := &in.AdditionalDisks, &out.AdditionalDisks
		*out = make([]apiv1beta1.AttachedDiskSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(apiv1beta1.ServiceAccount)
		(*in).DeepCopyInto(*out)
	}
	if in.ProvisioningModel != nil {
		in, out := &in.ProvisioningModel, &out.ProvisioningModel
		*out = new(apiv1beta1.ProvisioningModel)
		**out = **in
	}
	if in.IPForwarding != nil {
		in, out := &in.IPForwarding, &out.IPForwarding
		*out = new(apiv1beta1.IPForwarding)
		**out = **in
	}
	if in.ShieldedInstanceConfig != nil {
		in, out := &in.ShieldedInstanceConfig, &out.ShieldedInstanceConfig
		*out = new(apiv1beta1.GCPShieldedInstanceConfig)
		**out = **in
	}
	if in.OnHostMaintenance != nil {
		in, out := &in.OnHostMaintenance, &out.OnHostMaintenance
		*out = new(apiv1beta1.HostMaintenancePolicy)
		**out = **in
	}
	if in.ConfidentialCompute != nil {
		in, out := &in.ConfidentialCompute, &out.ConfidentialCompute
		*out = new(apiv1beta1.ConfidentialComputePolicy)
		**out = **in
	}
	if in.RootDiskEncryptionKey != nil {
		in, out := &in.RootDiskEncryptionKey, &out.RootDiskEncryptionKey
		*out = new(apiv1beta1.CustomerEncryptionKey)
		(*in).DeepCopyInto(*out)
	}
	if in.GuestAccelerators != nil {
		in, out := &in.GuestAccelerators, &out.GuestAccelerators
		*out = make([]apiv1beta1.Accelerator, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPMachinePoolSpec.
func (in *GCPMachinePoolSpec) DeepCopy() *GCPMachinePoolSpec {
	if in == nil {
		return nil
	}
	out := new(GCPMachinePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPMachinePoolStatus) DeepCopyInto(out *GCPMachinePoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPMachinePoolStatus.
func (in *GCPMachinePoolStatus) DeepCopy() *GCPMachinePoolStatus {
	if in == nil {
		return nil
	}
	out := new(GCPMachinePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedCluster) DeepCopyInto(out *GCPManagedCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedCluster.
func (in *GCPManagedCluster) DeepCopy() *GCPManagedCluster {
	if in == nil {
		return nil
	}
	out := new(GCPManagedCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPManagedCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedClusterList) DeepCopyInto(out *GCPManagedClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPManagedCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedClusterList.
func (in *GCPManagedClusterList) DeepCopy() *GCPManagedClusterList {
	if in == nil {
		return nil
	}
	out := new(GCPManagedClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPManagedClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedClusterSpec) DeepCopyInto(out *GCPManagedClusterSpec) {
	*out = *in
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	in.Network.DeepCopyInto(&out.Network)
	if in.AdditionalLabels != nil {
		in, out := &in.AdditionalLabels, &out.AdditionalLabels
		*out = make(apiv1beta1.Labels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ResourceManagerTags != nil {
		in, out := &in.ResourceManagerTags, &out.ResourceManagerTags
		*out = make(apiv1beta1.ResourceManagerTags, len(*in))
		copy(*out, *in)
	}
	if in.CredentialsRef != nil {
		in, out := &in.CredentialsRef, &out.CredentialsRef
		*out = new(apiv1beta1.ObjectReference)
		**out = **in
	}
	in.LoadBalancer.DeepCopyInto(&out.LoadBalancer)
	if in.ServiceEndpoints != nil {
		in, out := &in.ServiceEndpoints, &out.ServiceEndpoints
		*out = new(apiv1beta1.ServiceEndpoints)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedClusterSpec.
func (in *GCPManagedClusterSpec) DeepCopy() *GCPManagedClusterSpec {
	if in == nil {
		return nil
	}
	out := new(GCPManagedClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedClusterStatus) DeepCopyInto(out *GCPManagedClusterStatus) {
	*out = *in
	if in.FailureDomains != nil {
		in, out := &in.FailureDomains, &out.FailureDomains
		*out = make(corev1beta1.FailureDomains, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.Network.DeepCopyInto(&out.Network)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(corev1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedClusterStatus.
func (in *GCPManagedClusterStatus) DeepCopy() *GCPManagedClusterStatus {
	if in == nil {
		return nil
	}
	out := new(GCPManagedClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedClusterTemplate) DeepCopyInto(out *GCPManagedClusterTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedClusterTemplate.
func (in *GCPManagedClusterTemplate) DeepCopy() *GCPManagedClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(GCPManagedClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPManagedClusterTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedClusterTemplateList) DeepCopyInto(out *GCPManagedClusterTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPManagedClusterTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedClusterTemplateList.
func (in *GCPManagedClusterTemplateList) DeepCopy() *GCPManagedClusterTemplateList {
	if in == nil {
		return nil
	}
	out := new(GCPManagedClusterTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPManagedClusterTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedClusterTemplateResource) DeepCopyInto(out *GCPManagedClusterTemplateResource) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedClusterTemplateResource.
func (in *GCPManagedClusterTemplateResource) DeepCopy() *GCPManagedClusterTemplateResource {
	if in == nil {
		return nil
	}
	out := new(GCPManagedClusterTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedClusterTemplateResourceSpec) DeepCopyInto(out *GCPManagedClusterTemplateResourceSpec) {
	*out = *in
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	in.Network.DeepCopyInto(&out.Network)
	if in.AdditionalLabels != nil {
		in, out := &in.AdditionalLabels, &out.AdditionalLabels
		*out = make(apiv1beta1.Labels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ResourceManagerTags != nil {
		in, out := &in.ResourceManagerTags, &out.ResourceManagerTags
		*out = make(apiv1beta1.ResourceManagerTags, len(*in))
		copy(*out, *in)
	}
	if in.CredentialsRef != nil {
		in, out := &in.CredentialsRef, &out.CredentialsRef
		*out = new(apiv1beta1.ObjectReference)
		**out = **in
	}
	in.LoadBalancer.DeepCopyInto(&out.LoadBalancer)
	if in.ServiceEndpoints != nil {
		in, out := &in.ServiceEndpoints, &out.ServiceEndpoints
		*out = new(apiv1beta1.ServiceEndpoints)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedClusterTemplateResourceSpec.
func (in *GCPManagedClusterTemplateResourceSpec) DeepCopy() *GCPManagedClusterTemplateResourceSpec {
	if in == nil {
		return nil
	}
	out := new(GCPManagedClusterTemplateResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedClusterTemplateSpec) DeepCopyInto(out *GCPManagedClusterTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedClusterTemplateSpec.
func (in *GCPManagedClusterTemplateSpec) DeepCopy() *GCPManagedClusterTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(GCPManagedClusterTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedControlPlane) DeepCopyInto(out *GCPManagedControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedControlPlane.
func (in *GCPManagedControlPlane) DeepCopy() *GCPManagedControlPlane {
	if in == nil {
		return nil
	}
	out := new(GCPManagedControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPManagedControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedControlPlaneClassSpec) DeepCopyInto(out *GCPManagedControlPlaneClassSpec) {
	*out = *in
	if in.MachineTemplate != nil {
		in, out := &in.MachineTemplate, &out.MachineTemplate
		*out = new(GCPManagedControlPlaneTemplateMachineTemplate)
		**out = **in
	}
	if in.ClusterNetwork != nil {
		in, out := &in.ClusterNetwork, &out.ClusterNetwork
		*out = new(ClusterNetwork)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterSecurity != nil {
		in, out := &in.ClusterSecurity, &out.ClusterSecurity
		*out = new(ClusterSecurity)
		(*in).DeepCopyInto(*out)
	}
	if in.ReleaseChannel != nil {
		in, out := &in.ReleaseChannel, &out.ReleaseChannel
		*out = new(ReleaseChannel)
		**out = **in
	}
	if in.BinaryAuthorization != nil {
		in, out := &in.BinaryAuthorization, &out.BinaryAuthorization
		*out = new(BinaryAuthorization)
		**out = **in
	}
	if in.MasterAuthorizedNetworksConfig != nil {
		in, out := &in.MasterAuthorizedNetworksConfig, &out.MasterAuthorizedNetworksConfig
		*out = new(MasterAuthorizedNetworksConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.LoggingService != nil {
		in, out := &in.LoggingService, &out.LoggingService
		*out = new(LoggingService)
		**out = **in
	}
	if in.MonitoringService != nil {
		in, out := &in.MonitoringService, &out.MonitoringService
		*out = new(MonitoringService)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedControlPlaneClassSpec.
func (in *GCPManagedControlPlaneClassSpec) DeepCopy() *GCPManagedControlPlaneClassSpec {
	if in == nil {
		return nil
	}
	out := new(GCPManagedControlPlaneClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedControlPlaneList) DeepCopyInto(out *GCPManagedControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPManagedControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedControlPlaneList.
func (in *GCPManagedControlPlaneList) DeepCopy() *GCPManagedControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(GCPManagedControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPManagedControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedControlPlaneSpec) DeepCopyInto(out *GCPManagedControlPlaneSpec) {
	*out = *in
	in.GCPManagedControlPlaneClassSpec.DeepCopyInto(&out.GCPManagedControlPlaneClassSpec)
	if in.ControlPlaneVersion != nil {
		in, out := &in.ControlPlaneVersion, &out.ControlPlaneVersion
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	out.Endpoint = in.Endpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedControlPlaneSpec.
func (in *GCPManagedControlPlaneSpec) DeepCopy() *GCPManagedControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(GCPManagedControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedControlPlaneStatus) DeepCopyInto(out *GCPManagedControlPlaneStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(corev1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedControlPlaneStatus.
func (in *GCPManagedControlPlaneStatus) DeepCopy() *GCPManagedControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(GCPManagedControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedControlPlaneTemplate) DeepCopyInto(out *GCPManagedControlPlaneTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedControlPlaneTemplate.
func (in *GCPManagedControlPlaneTemplate) DeepCopy() *GCPManagedControlPlaneTemplate {
	if in == nil {
		return nil
	}
	out := new(GCPManagedControlPlaneTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPManagedControlPlaneTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedControlPlaneTemplateList) DeepCopyInto(out *GCPManagedControlPlaneTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPManagedControlPlaneTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedControlPlaneTemplateList.
func (in *GCPManagedControlPlaneTemplateList) DeepCopy() *GCPManagedControlPlaneTemplateList {
	if in == nil {
		return nil
	}
	out := new(GCPManagedControlPlaneTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPManagedControlPlaneTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedControlPlaneTemplateMachineTemplate) DeepCopyInto(out *GCPManagedControlPlaneTemplateMachineTemplate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedControlPlaneTemplateMachineTemplate.
func (in *GCPManagedControlPlaneTemplateMachineTemplate) DeepCopy() *GCPManagedControlPlaneTemplateMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(GCPManagedControlPlaneTemplateMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedControlPlaneTemplateResource) DeepCopyInto(out *GCPManagedControlPlaneTemplateResource) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedControlPlaneTemplateResource.
func (in *GCPManagedControlPlaneTemplateResource) DeepCopy() *GCPManagedControlPlaneTemplateResource {
	if in == nil {
		return nil
	}
	out := new(GCPManagedControlPlaneTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedControlPlaneTemplateResourceSpec) DeepCopyInto(out *GCPManagedControlPlaneTemplateResourceSpec) {
	*out = *in
	in.GCPManagedControlPlaneClassSpec.DeepCopyInto(&out.GCPManagedControlPlaneClassSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedControlPlaneTemplateResourceSpec.
func (in *GCPManagedControlPlaneTemplateResourceSpec) DeepCopy() *GCPManagedControlPlaneTemplateResourceSpec {
	if in == nil {
		return nil
	}
	out := new(GCPManagedControlPlaneTemplateResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedControlPlaneTemplateSpec) DeepCopyInto(out *GCPManagedControlPlaneTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedControlPlaneTemplateSpec.
func (in *GCPManagedControlPlaneTemplateSpec) DeepCopy() *GCPManagedControlPlaneTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(GCPManagedControlPlaneTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedMachinePool) DeepCopyInto(out *GCPManagedMachinePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedMachinePool.
func (in *GCPManagedMachinePool) DeepCopy() *GCPManagedMachinePool {
	if in == nil {
		return nil
	}
	out := new(GCPManagedMachinePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPManagedMachinePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedMachinePoolClassSpec) DeepCopyInto(out *GCPManagedMachinePoolClassSpec) {
	*out = *in
	if in.MachineType != nil {
		in, out := &in.MachineType, &out.MachineType
		*out = new(string)
		**out = **in
	}
	if in.DiskSizeGb != nil {
		in, out := &in.DiskSizeGb, &out.DiskSizeGb
		*out = new(int32)
		**out = **in
	}
	if in.LocalSsdCount != nil {
		in, out := &in.LocalSsdCount, &out.LocalSsdCount
		*out = new(int32)
		**out = **in
	}
	if in.Scaling != nil {
		in, out := &in.Scaling, &out.Scaling
		*out = new(NodePoolAutoScaling)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeLocations != nil {
		in, out := &in.NodeLocations, &out.NodeLocations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ImageType != nil {
		in, out := &in.ImageType, &out.ImageType
		*out = new(string)
		**out = **in
	}
	if in.InstanceType != nil {
		in, out := &in.InstanceType, &out.InstanceType
		*out = new(string)
		**out = **in
	}
	if in.DiskType != nil {
		in, out := &in.DiskType, &out.DiskType
		*out = new(DiskType)
		**out = **in
	}
	if in.DiskSizeGB != nil {
		in, out := &in.DiskSizeGB, &out.DiskSizeGB
		*out = new(int64)
		**out = **in
	}
	if in.MaxPodsPerNode != nil {
		in, out := &in.MaxPodsPerNode, &out.MaxPodsPerNode
		*out = new(int64)
		**out = **in
	}
	in.NodeNetwork.DeepCopyInto(&out.NodeNetwork)
	in.NodeSecurity.DeepCopyInto(&out.NodeSecurity)
	if in.KubernetesLabels != nil {
		in, out := &in.KubernetesLabels, &out.KubernetesLabels
		*out = make(apiv1beta1.Labels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.KubernetesTaints != nil {
		in, out := &in.KubernetesTaints, &out.KubernetesTaints
		*out = make(Taints, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalLabels != nil {
		in, out := &in.AdditionalLabels, &out.AdditionalLabels
		*out = make(apiv1beta1.Labels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Management != nil {
		in, out := &in.Management, &out.Management
		*out = new(NodePoolManagement)
		**out = **in
	}
	if in.LinuxNodeConfig != nil {
		in, out := &in.LinuxNodeConfig, &out.LinuxNodeConfig
		*out = new(LinuxNodeConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedMachinePoolClassSpec.
func (in *GCPManagedMachinePoolClassSpec) DeepCopy() *GCPManagedMachinePoolClassSpec {
	if in == nil {
		return nil
	}
	out := new(GCPManagedMachinePoolClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedMachinePoolList) DeepCopyInto(out *GCPManagedMachinePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPManagedMachinePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedMachinePoolList.
func (in *GCPManagedMachinePoolList) DeepCopy() *GCPManagedMachinePoolList {
	if in == nil {
		return nil
	}
	out := new(GCPManagedMachinePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPManagedMachinePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedMachinePoolSpec) DeepCopyInto(out *GCPManagedMachinePoolSpec) {
	*out = *in
	in.GCPManagedMachinePoolClassSpec.DeepCopyInto(&out.GCPManagedMachinePoolClassSpec)
	if in.ProviderIDList != nil {
		in, out := &in.ProviderIDList, &out.ProviderIDList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedMachinePoolSpec.
func (in *GCPManagedMachinePoolSpec) DeepCopy() *GCPManagedMachinePoolSpec {
	if in == nil {
		return nil
	}
	out := new(GCPManagedMachinePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedMachinePoolStatus) DeepCopyInto(out *GCPManagedMachinePoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(corev1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedMachinePoolStatus.
func (in *GCPManagedMachinePoolStatus) DeepCopy() *GCPManagedMachinePoolStatus {
	if in == nil {
		return nil
	}
	out := new(GCPManagedMachinePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedMachinePoolTemplate) DeepCopyInto(out *GCPManagedMachinePoolTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedMachinePoolTemplate.
func (in *GCPManagedMachinePoolTemplate) DeepCopy() *GCPManagedMachinePoolTemplate {
	if in == nil {
		return nil
	}
	out := new(GCPManagedMachinePoolTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPManagedMachinePoolTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedMachinePoolTemplateList) DeepCopyInto(out *GCPManagedMachinePoolTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPManagedMachinePoolTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedMachinePoolTemplateList.
func (in *GCPManagedMachinePoolTemplateList) DeepCopy() *GCPManagedMachinePoolTemplateList {
	if in == nil {
		return nil
	}
	out := new(GCPManagedMachinePoolTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPManagedMachinePoolTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedMachinePoolTemplateResource) DeepCopyInto(out *GCPManagedMachinePoolTemplateResource) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedMachinePoolTemplateResource.
func (in *GCPManagedMachinePoolTemplateResource) DeepCopy() *GCPManagedMachinePoolTemplateResource {
	if in == nil {
		return nil
	}
	out := new(GCPManagedMachinePoolTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedMachinePoolTemplateResourceSpec) DeepCopyInto(out *GCPManagedMachinePoolTemplateResourceSpec) {
	*out = *in
	in.GCPManagedMachinePoolClassSpec.DeepCopyInto(&out.GCPManagedMachinePoolClassSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedMachinePoolTemplateResourceSpec.
func (in *GCPManagedMachinePoolTemplateResourceSpec) DeepCopy() *GCPManagedMachinePoolTemplateResourceSpec {
	if in == nil {
		return nil
	}
	out := new(GCPManagedMachinePoolTemplateResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPManagedMachinePoolTemplateSpec) DeepCopyInto(out *GCPManagedMachinePoolTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPManagedMachinePoolTemplateSpec.
func (in *GCPManagedMachinePoolTemplateSpec) DeepCopy() *GCPManagedMachinePoolTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(GCPManagedMachinePoolTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KCCIPAllocationPolicy) DeepCopyInto(out *KCCIPAllocationPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KCCIPAllocationPolicy.
func (in *KCCIPAllocationPolicy) DeepCopy() *KCCIPAllocationPolicy {
	if in == nil {
		return nil
	}
	out := new(KCCIPAllocationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KCCMasterAuthorizedNetworksCidrBlock) DeepCopyInto(out *KCCMasterAuthorizedNetworksCidrBlock) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KCCMasterAuthorizedNetworksCidrBlock.
func (in *KCCMasterAuthorizedNetworksCidrBlock) DeepCopy() *KCCMasterAuthorizedNetworksCidrBlock {
	if in == nil {
		return nil
	}
	out := new(KCCMasterAuthorizedNetworksCidrBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KCCMasterAuthorizedNetworksConfig) DeepCopyInto(out *KCCMasterAuthorizedNetworksConfig) {
	*out = *in
	if in.CidrBlocks != nil {
		in, out := &in.CidrBlocks, &out.CidrBlocks
		*out = make([]KCCMasterAuthorizedNetworksCidrBlock, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KCCMasterAuthorizedNetworksConfig.
func (in *KCCMasterAuthorizedNetworksConfig) DeepCopy() *KCCMasterAuthorizedNetworksConfig {
	if in == nil {
		return nil
	}
	out := new(KCCMasterAuthorizedNetworksConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KCCNodeConfig) DeepCopyInto(out *KCCNodeConfig) {
	*out = *in
	if in.DiskSizeGb != nil {
		in, out := &in.DiskSizeGb, &out.DiskSizeGb
		*out = new(int32)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OauthScopes != nil {
		in, out := &in.OauthScopes, &out.OauthScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServiceAccountRef != nil {
		in, out := &in.ServiceAccountRef, &out.ServiceAccountRef
		*out = new(KCCResourceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KCCNodeConfig.
func (in *KCCNodeConfig) DeepCopy() *KCCNodeConfig {
	if in == nil {
		return nil
	}
	out := new(KCCNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KCCNodePoolAutoscaling) DeepCopyInto(out *KCCNodePoolAutoscaling) {
	*out = *in
	if in.MinNodeCount != nil {
		in, out := &in.MinNodeCount, &out.MinNodeCount
		*out = new(int32)
		**out = **in
	}
	if in.MaxNodeCount != nil {
		in, out := &in.MaxNodeCount, &out.MaxNodeCount
		*out = new(int32)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KCCNodePoolAutoscaling.
func (in *KCCNodePoolAutoscaling) DeepCopy() *KCCNodePoolAutoscaling {
	if in == nil {
		return nil
	}
	out := new(KCCNodePoolAutoscaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KCCNodePoolManagement) DeepCopyInto(out *KCCNodePoolManagement) {
	*out = *in
	if in.AutoUpgrade != nil {
		in, out := &in.AutoUpgrade, &out.AutoUpgrade
		*out = new(bool)
		**out = **in
	}
	if in.AutoRepair != nil {
		in, out := &in.AutoRepair, &out.AutoRepair
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KCCNodePoolManagement.
func (in *KCCNodePoolManagement) DeepCopy() *KCCNodePoolManagement {
	if in == nil {
		return nil
	}
	out := new(KCCNodePoolManagement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KCCObjectMeta) DeepCopyInto(out *KCCObjectMeta) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KCCObjectMeta.
func (in *KCCObjectMeta) DeepCopy() *KCCObjectMeta {
	if in == nil {
		return nil
	}
	out := new(KCCObjectMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KCCPrivateClusterConfig) DeepCopyInto(out *KCCPrivateClusterConfig) {
	*out = *in
	if in.EnablePrivateEndpoint != nil {
		in, out := &in.EnablePrivateEndpoint, &out.EnablePrivateEndpoint
		*out = new(bool)
		**out = **in
	}
	if in.EnablePrivateNodes != nil {
		in, out := &in.EnablePrivateNodes, &out.EnablePrivateNodes
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KCCPrivateClusterConfig.
func (in *KCCPrivateClusterConfig) DeepCopy() *KCCPrivateClusterConfig {
	if in == nil {
		return nil
	}
	out := new(KCCPrivateClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KCCReleaseChannel) DeepCopyInto(out *KCCReleaseChannel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KCCReleaseChannel.
func (in *KCCReleaseChannel) DeepCopy() *KCCReleaseChannel {
	if in == nil {
		return nil
	}
	out := new(KCCReleaseChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KCCResourceRef) DeepCopyInto(out *KCCResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KCCResourceRef.
func (in *KCCResourceRef) DeepCopy() *KCCResourceRef {
	if in == nil {
		return nil
	}
	out := new(KCCResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KCCSecondaryIPRange) DeepCopyInto(out *KCCSecondaryIPRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KCCSecondaryIPRange.
func (in *KCCSecondaryIPRange) DeepCopy() *KCCSecondaryIPRange {
	if in == nil {
		return nil
	}
	out := new(KCCSecondaryIPRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KCCWorkloadIdentityConfig) DeepCopyInto(out *KCCWorkloadIdentityConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KCCWorkloadIdentityConfig.
func (in *KCCWorkloadIdentityConfig) DeepCopy() *KCCWorkloadIdentityConfig {
	if in == nil {
		return nil
	}
	out := new(KCCWorkloadIdentityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinuxNodeConfig) DeepCopyInto(out *LinuxNodeConfig) {
	*out = *in
	if in.Sysctls != nil {
		in, out := &in.Sysctls, &out.Sysctls
		*out = make([]SysctlConfig, len(*in))
		copy(*out, *in)
	}
	if in.CgroupMode != nil {
		in, out := &in.CgroupMode, &out.CgroupMode
		*out = new(ManagedNodePoolCgroupMode)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinuxNodeConfig.
func (in *LinuxNodeConfig) DeepCopy() *LinuxNodeConfig {
	if in == nil {
		return nil
	}
	out := new(LinuxNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterAuthorizedNetworksConfig) DeepCopyInto(out *MasterAuthorizedNetworksConfig) {
	*out = *in
	if in.CidrBlocks != nil {
		in, out := &in.CidrBlocks, &out.CidrBlocks
		*out = make([]*MasterAuthorizedNetworksConfigCidrBlock, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(MasterAuthorizedNetworksConfigCidrBlock)
				**out = **in
			}
		}
	}
	if in.GcpPublicCidrsAccessEnabled != nil {
		in, out := &in.GcpPublicCidrsAccessEnabled, &out.GcpPublicCidrsAccessEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterAuthorizedNetworksConfig.
func (in *MasterAuthorizedNetworksConfig) DeepCopy() *MasterAuthorizedNetworksConfig {
	if in == nil {
		return nil
	}
	out := new(MasterAuthorizedNetworksConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterAuthorizedNetworksConfigCidrBlock) DeepCopyInto(out *MasterAuthorizedNetworksConfigCidrBlock) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterAuthorizedNetworksConfigCidrBlock.
func (in *MasterAuthorizedNetworksConfigCidrBlock) DeepCopy() *MasterAuthorizedNetworksConfigCidrBlock {
	if in == nil {
		return nil
	}
	out := new(MasterAuthorizedNetworksConfigCidrBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetworkConfig) DeepCopyInto(out *NodeNetworkConfig) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CreatePodRange != nil {
		in, out := &in.CreatePodRange, &out.CreatePodRange
		*out = new(bool)
		**out = **in
	}
	if in.PodRangeName != nil {
		in, out := &in.PodRangeName, &out.PodRangeName
		*out = new(string)
		**out = **in
	}
	if in.PodRangeCidrBlock != nil {
		in, out := &in.PodRangeCidrBlock, &out.PodRangeCidrBlock
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetworkConfig.
func (in *NodeNetworkConfig) DeepCopy() *NodeNetworkConfig {
	if in == nil {
		return nil
	}
	out := new(NodeNetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolAutoScaling) DeepCopyInto(out *NodePoolAutoScaling) {
	*out = *in
	if in.MinCount != nil {
		in, out := &in.MinCount, &out.MinCount
		*out = new(int32)
		**out = **in
	}
	if in.MaxCount != nil {
		in, out := &in.MaxCount, &out.MaxCount
		*out = new(int32)
		**out = **in
	}
	if in.EnableAutoscaling != nil {
		in, out := &in.EnableAutoscaling, &out.EnableAutoscaling
		*out = new(bool)
		**out = **in
	}
	if in.LocationPolicy != nil {
		in, out := &in.LocationPolicy, &out.LocationPolicy
		*out = new(ManagedNodePoolLocationPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolAutoScaling.
func (in *NodePoolAutoScaling) DeepCopy() *NodePoolAutoScaling {
	if in == nil {
		return nil
	}
	out := new(NodePoolAutoScaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolManagement) DeepCopyInto(out *NodePoolManagement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolManagement.
func (in *NodePoolManagement) DeepCopy() *NodePoolManagement {
	if in == nil {
		return nil
	}
	out := new(NodePoolManagement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSecurityConfig) DeepCopyInto(out *NodeSecurityConfig) {
	*out = *in
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
	if in.SandboxType != nil {
		in, out := &in.SandboxType, &out.SandboxType
		*out = new(string)
		**out = **in
	}
	if in.EnableSecureBoot != nil {
		in, out := &in.EnableSecureBoot, &out.EnableSecureBoot
		*out = new(bool)
		**out = **in
	}
	if in.EnableIntegrityMonitoring != nil {
		in, out := &in.EnableIntegrityMonitoring, &out.EnableIntegrityMonitoring
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSecurityConfig.
func (in *NodeSecurityConfig) DeepCopy() *NodeSecurityConfig {
	if in == nil {
		return nil
	}
	out := new(NodeSecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateCluster) DeepCopyInto(out *PrivateCluster) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateCluster.
func (in *PrivateCluster) DeepCopy() *PrivateCluster {
	if in == nil {
		return nil
	}
	out := new(PrivateCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountConfig) DeepCopyInto(out *ServiceAccountConfig) {
	*out = *in
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountConfig.
func (in *ServiceAccountConfig) DeepCopy() *ServiceAccountConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SysctlConfig) DeepCopyInto(out *SysctlConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SysctlConfig.
func (in *SysctlConfig) DeepCopy() *SysctlConfig {
	if in == nil {
		return nil
	}
	out := new(SysctlConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Taint) DeepCopyInto(out *Taint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Taint.
func (in *Taint) DeepCopy() *Taint {
	if in == nil {
		return nil
	}
	out := new(Taint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Taints) DeepCopyInto(out *Taints) {
	{
		in := &in
		*out = make(Taints, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Taints.
func (in Taints) DeepCopy() Taints {
	if in == nil {
		return nil
	}
	out := new(Taints)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadIdentityConfig) DeepCopyInto(out *WorkloadIdentityConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadIdentityConfig.
func (in *WorkloadIdentityConfig) DeepCopy() *WorkloadIdentityConfig {
	if in == nil {
		return nil
	}
	out := new(WorkloadIdentityConfig)
	in.DeepCopyInto(out)
	return out
}
