//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	corev1beta2 "sigs.k8s.io/cluster-api/api/core/v1beta2"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedCluster) DeepCopyInto(out *GCPKCCManagedCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedCluster.
func (in *GCPKCCManagedCluster) DeepCopy() *GCPKCCManagedCluster {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedClusterInitializationStatus) DeepCopyInto(out *GCPKCCManagedClusterInitializationStatus) {
	*out = *in
	if in.Provisioned != nil {
		in, out := &in.Provisioned, &out.Provisioned
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedClusterInitializationStatus.
func (in *GCPKCCManagedClusterInitializationStatus) DeepCopy() *GCPKCCManagedClusterInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedClusterInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedClusterList) DeepCopyInto(out *GCPKCCManagedClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPKCCManagedCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedClusterList.
func (in *GCPKCCManagedClusterList) DeepCopy() *GCPKCCManagedClusterList {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedClusterSpec) DeepCopyInto(out *GCPKCCManagedClusterSpec) {
	*out = *in
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Subnetwork != nil {
		in, out := &in.Subnetwork, &out.Subnetwork
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedClusterSpec.
func (in *GCPKCCManagedClusterSpec) DeepCopy() *GCPKCCManagedClusterSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedClusterStatus) DeepCopyInto(out *GCPKCCManagedClusterStatus) {
	*out = *in
	if in.Initialization != nil {
		in, out := &in.Initialization, &out.Initialization
		*out = new(GCPKCCManagedClusterInitializationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.FailureDomains != nil {
		in, out := &in.FailureDomains, &out.FailureDomains
		*out = make([]corev1beta2.FailureDomain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedClusterStatus.
func (in *GCPKCCManagedClusterStatus) DeepCopy() *GCPKCCManagedClusterStatus {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedClusterTemplate) DeepCopyInto(out *GCPKCCManagedClusterTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedClusterTemplate.
func (in *GCPKCCManagedClusterTemplate) DeepCopy() *GCPKCCManagedClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedClusterTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedClusterTemplateList) DeepCopyInto(out *GCPKCCManagedClusterTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPKCCManagedClusterTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedClusterTemplateList.
func (in *GCPKCCManagedClusterTemplateList) DeepCopy() *GCPKCCManagedClusterTemplateList {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedClusterTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedClusterTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedClusterTemplateResource) DeepCopyInto(out *GCPKCCManagedClusterTemplateResource) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedClusterTemplateResource.
func (in *GCPKCCManagedClusterTemplateResource) DeepCopy() *GCPKCCManagedClusterTemplateResource {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedClusterTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedClusterTemplateResourceSpec) DeepCopyInto(out *GCPKCCManagedClusterTemplateResourceSpec) {
	*out = *in
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Subnetwork != nil {
		in, out := &in.Subnetwork, &out.Subnetwork
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedClusterTemplateResourceSpec.
func (in *GCPKCCManagedClusterTemplateResourceSpec) DeepCopy() *GCPKCCManagedClusterTemplateResourceSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedClusterTemplateResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedClusterTemplateSpec) DeepCopyInto(out *GCPKCCManagedClusterTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedClusterTemplateSpec.
func (in *GCPKCCManagedClusterTemplateSpec) DeepCopy() *GCPKCCManagedClusterTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedClusterTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedControlPlane) DeepCopyInto(out *GCPKCCManagedControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedControlPlane.
func (in *GCPKCCManagedControlPlane) DeepCopy() *GCPKCCManagedControlPlane {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedControlPlaneInitializationStatus) DeepCopyInto(out *GCPKCCManagedControlPlaneInitializationStatus) {
	*out = *in
	if in.ControlPlaneInitialized != nil {
		in, out := &in.ControlPlaneInitialized, &out.ControlPlaneInitialized
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedControlPlaneInitializationStatus.
func (in *GCPKCCManagedControlPlaneInitializationStatus) DeepCopy() *GCPKCCManagedControlPlaneInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedControlPlaneInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedControlPlaneList) DeepCopyInto(out *GCPKCCManagedControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPKCCManagedControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedControlPlaneList.
func (in *GCPKCCManagedControlPlaneList) DeepCopy() *GCPKCCManagedControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedControlPlaneSpec) DeepCopyInto(out *GCPKCCManagedControlPlaneSpec) {
	*out = *in
	if in.ContainerCluster != nil {
		in, out := &in.ContainerCluster, &out.ContainerCluster
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedControlPlaneSpec.
func (in *GCPKCCManagedControlPlaneSpec) DeepCopy() *GCPKCCManagedControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedControlPlaneStatus) DeepCopyInto(out *GCPKCCManagedControlPlaneStatus) {
	*out = *in
	if in.Initialization != nil {
		in, out := &in.Initialization, &out.Initialization
		*out = new(GCPKCCManagedControlPlaneInitializationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalManagedControlPlane != nil {
		in, out := &in.ExternalManagedControlPlane, &out.ExternalManagedControlPlane
		*out = new(bool)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.ReadyReplicas != nil {
		in, out := &in.ReadyReplicas, &out.ReadyReplicas
		*out = new(int32)
		**out = **in
	}
	if in.AvailableReplicas != nil {
		in, out := &in.AvailableReplicas, &out.AvailableReplicas
		*out = new(int32)
		**out = **in
	}
	if in.UpToDateReplicas != nil {
		in, out := &in.UpToDateReplicas, &out.UpToDateReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedControlPlaneStatus.
func (in *GCPKCCManagedControlPlaneStatus) DeepCopy() *GCPKCCManagedControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedControlPlaneTemplate) DeepCopyInto(out *GCPKCCManagedControlPlaneTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedControlPlaneTemplate.
func (in *GCPKCCManagedControlPlaneTemplate) DeepCopy() *GCPKCCManagedControlPlaneTemplate {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedControlPlaneTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedControlPlaneTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedControlPlaneTemplateList) DeepCopyInto(out *GCPKCCManagedControlPlaneTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPKCCManagedControlPlaneTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedControlPlaneTemplateList.
func (in *GCPKCCManagedControlPlaneTemplateList) DeepCopy() *GCPKCCManagedControlPlaneTemplateList {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedControlPlaneTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedControlPlaneTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedControlPlaneTemplateResource) DeepCopyInto(out *GCPKCCManagedControlPlaneTemplateResource) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedControlPlaneTemplateResource.
func (in *GCPKCCManagedControlPlaneTemplateResource) DeepCopy() *GCPKCCManagedControlPlaneTemplateResource {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedControlPlaneTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedControlPlaneTemplateResourceSpec) DeepCopyInto(out *GCPKCCManagedControlPlaneTemplateResourceSpec) {
	*out = *in
	if in.ContainerCluster != nil {
		in, out := &in.ContainerCluster, &out.ContainerCluster
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedControlPlaneTemplateResourceSpec.
func (in *GCPKCCManagedControlPlaneTemplateResourceSpec) DeepCopy() *GCPKCCManagedControlPlaneTemplateResourceSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedControlPlaneTemplateResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedControlPlaneTemplateSpec) DeepCopyInto(out *GCPKCCManagedControlPlaneTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedControlPlaneTemplateSpec.
func (in *GCPKCCManagedControlPlaneTemplateSpec) DeepCopy() *GCPKCCManagedControlPlaneTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedControlPlaneTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedMachinePool) DeepCopyInto(out *GCPKCCManagedMachinePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedMachinePool.
func (in *GCPKCCManagedMachinePool) DeepCopy() *GCPKCCManagedMachinePool {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedMachinePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedMachinePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedMachinePoolInitializationStatus) DeepCopyInto(out *GCPKCCManagedMachinePoolInitializationStatus) {
	*out = *in
	if in.Provisioned != nil {
		in, out := &in.Provisioned, &out.Provisioned
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedMachinePoolInitializationStatus.
func (in *GCPKCCManagedMachinePoolInitializationStatus) DeepCopy() *GCPKCCManagedMachinePoolInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedMachinePoolInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedMachinePoolList) DeepCopyInto(out *GCPKCCManagedMachinePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPKCCManagedMachinePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedMachinePoolList.
func (in *GCPKCCManagedMachinePoolList) DeepCopy() *GCPKCCManagedMachinePoolList {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedMachinePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedMachinePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedMachinePoolSpec) DeepCopyInto(out *GCPKCCManagedMachinePoolSpec) {
	*out = *in
	if in.NodePool != nil {
		in, out := &in.NodePool, &out.NodePool
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.ProviderIDList != nil {
		in, out := &in.ProviderIDList, &out.ProviderIDList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedMachinePoolSpec.
func (in *GCPKCCManagedMachinePoolSpec) DeepCopy() *GCPKCCManagedMachinePoolSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedMachinePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedMachinePoolStatus) DeepCopyInto(out *GCPKCCManagedMachinePoolStatus) {
	*out = *in
	if in.Initialization != nil {
		in, out := &in.Initialization, &out.Initialization
		*out = new(GCPKCCManagedMachinePoolInitializationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedMachinePoolStatus.
func (in *GCPKCCManagedMachinePoolStatus) DeepCopy() *GCPKCCManagedMachinePoolStatus {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedMachinePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedMachinePoolTemplate) DeepCopyInto(out *GCPKCCManagedMachinePoolTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedMachinePoolTemplate.
func (in *GCPKCCManagedMachinePoolTemplate) DeepCopy() *GCPKCCManagedMachinePoolTemplate {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedMachinePoolTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedMachinePoolTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedMachinePoolTemplateList) DeepCopyInto(out *GCPKCCManagedMachinePoolTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPKCCManagedMachinePoolTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedMachinePoolTemplateList.
func (in *GCPKCCManagedMachinePoolTemplateList) DeepCopy() *GCPKCCManagedMachinePoolTemplateList {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedMachinePoolTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPKCCManagedMachinePoolTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedMachinePoolTemplateResource) DeepCopyInto(out *GCPKCCManagedMachinePoolTemplateResource) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedMachinePoolTemplateResource.
func (in *GCPKCCManagedMachinePoolTemplateResource) DeepCopy() *GCPKCCManagedMachinePoolTemplateResource {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedMachinePoolTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedMachinePoolTemplateResourceSpec) DeepCopyInto(out *GCPKCCManagedMachinePoolTemplateResourceSpec) {
	*out = *in
	if in.NodePool != nil {
		in, out := &in.NodePool, &out.NodePool
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedMachinePoolTemplateResourceSpec.
func (in *GCPKCCManagedMachinePoolTemplateResourceSpec) DeepCopy() *GCPKCCManagedMachinePoolTemplateResourceSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedMachinePoolTemplateResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKCCManagedMachinePoolTemplateSpec) DeepCopyInto(out *GCPKCCManagedMachinePoolTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKCCManagedMachinePoolTemplateSpec.
func (in *GCPKCCManagedMachinePoolTemplateSpec) DeepCopy() *GCPKCCManagedMachinePoolTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(GCPKCCManagedMachinePoolTemplateSpec)
	in.DeepCopyInto(out)
	return out
}
